yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthor.as_view(), name='author'),
    path('tech/', views.AboutTech.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

CACHE_SEC = 0

urlpatterns = [
    path('', views.PostIndex.as_view(),
         name='index'),
    path('group/<slug:slug>/',
         views.PostGroup.as_view(),
         name='group_list'),
    path('profile/<str:username>/',
         views.PostProfile.as_view(),
         name='profile'),
    path('posts/<int:post_id>/', views.PostDetail.as_view(),
         name='post_detail'),
    path('create/', views.PostCreate.as_view(),
         name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.PostCommentAdd.as_view(),
         name='add_comment'),
    path('follow/', views.FollowIndex.as_view(),
         name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.ProfileFollow.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.ProfileUnfollow.as_view(),
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/like/',
        views.LikePost.as_view(),
        name='post_like'
    ),
    path(
        'posts/<int:post_id>/unlike/',
        views.UnlikePost.as_view(),
        name='post_unlike'
    ),
    path('posts/<int:post_id>/delete/', views.PostDelete.as_view(),
         name='post_delete'),
    path('posts/com/<int:comment_id>/delete/',
         views.CommentDelete.as_view(),
         name='comment_delete'),
    path('search/', views.PostTextSearch.as_view(), name='search')
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordChangeView
)
from django.views.generic import TemplateView
from .views import UserEditor
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_change/done/',
        PasswordChangeView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    # path('info/', TemplateView.as_view(
    #     template_name='users/includes/info_last.html',
    # ),
    #      name='info_last'
    #      ),
    path('info/', views.UserInfo.as_view(), name='info_last'),
    path('user/edit/', UserEditor.as_view(), name='user_edit'),
    path('info/comments/', TemplateView.as_view(
        template_name='users/includes/info_comments.html'
    ), name='info_comments'),
    path('info/posts/', TemplateView.as_view(
        template_name='users/includes/info_posts.html'
    ), name='info_posts'),
    path('info/likes/', TemplateView.as_view(
        template_name='users/includes/info_likes.html'
    ), name='info_likes'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.bad_request'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        # Add all the fields you want a user to change
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView, UpdateView, TemplateView
from django.urls import reverse_lazy
from .forms import CreationForm, UserUpdateForm
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from posts.models import Post, Like, Comment, Follow

User = get_user_model()


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class UserEditor(UpdateView):
    model = User
    template_name = 'users/user_edit.html'
    extra_context = {'is_edit': True}
    form_class = UserUpdateForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None,
                               instance=request.user
                               )
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
        return redirect(
            'users:info_last'
        )

    def get_object(self, queryset=None):
        print(User.objects.get(username=self.request.user.username))
        user = User.objects.get(username=self.request.user.username)
        return user


class UserInfo(TemplateView):
    template_name = 'users/includes/info_last.html'

    def get_context_data(self, **kwargs):
        context = super(UserInfo, self).get_context_data(**kwargs)
        user = self.request.user
        posts = Post.objects.filter(author=user)
        last_likes = Like.objects.filter(post__author=user).exclude(user=user)
        last_comments = Comment.objects.exclude(author=user).filter(post__author=user)
        last_follows = Follow.objects.filter(author=user)

        context.update({
            'posts': posts,
            'last_likes': last_likes,
            'last_comments': last_comments,
            'last_follows': last_follows,
        })
        return context

yatube/templates/users/includes/info_comments.html
{% extends 'users/user_info.html' %}
{% block header %}
Последние комментарии
{% endblock %}
{% block user %}
{% if user.comments.count == 0 %}
Вы не оставили еще ни одного комментария :(
{% else %}
{% for comment in user.comments.all|slice:':5' %}
<div class="card my-4">
<dd class="list-group list-group-flush">
    <li class="card-header">
        <a class="link-secondary" href="{% url 'posts:post_detail' comment.post.id %}"> {{ comment.post.text|slice:':250' }} </a>
    </li>
    <li class="list-group-item">
        <span class="figure-caption text-muted" style="float: right">
            {{ comment.pub_date }}
        </span>
      {{ comment }}
    </li>
</dd>
</div>
{% endfor %}
{% endif %}
{% endblock %}

yatube/templates/users/includes/info_last.html
{% extends 'users/user_info.html' %}
{% load humanize %}
{% block header %}
Последние обновления
{% endblock %}
{% block user %}



{% if not last_likes and not last_comments %}
<div class="card-text">Нету новых уведомлений.</div>
{% endif %}



{% if last_likes %}
<div class="card">
  <ul class="list-group list-group-flush">
    <dd class="card-header text-muted">Лайки</dd>
      {% for like in last_likes|slice:':4' %}
    <li class="list-group-item"><a class="link-secondary" href="{% url 'posts:profile' like.user %}">
        {% if like.user.first_name %}{{ like.user.first_name }}{% else %}{{ like.user }}{% endif %}</a>
        оценил(а) вашу
        <a class="link-secondary" href="{% url 'posts:post_detail' like.post.id %}">публикацию</a>.
        <span style="float: right" class="text-muted small">{{ like.pub_date | naturalday }} в {{ like.pub_date|date:'H:m' }}</span>
    </li>
      {% endfor %}
      {% if last_likes.count > 4 %}
    <li class="list-group-item">
      Еще {{ last_likes.count | add:'-4' }}
    </li>
      {% endif %}
  </ul>
</div>
<br>
{% endif %}


{% if last_comments %}
<div class="card">
  <ul class="list-group list-group-flush">
    <dd class="card-header text-muted">Комментарии</dd>
      {% for comment in last_comments|slice:':4' %}
    <li class="list-group-item"><a class="link-secondary" href="{% url 'posts:profile' comment.author %}">
        {% if comment.author.first_name %}{{ comment.author.first_name }}{% else %}{{ comment.author }}{% endif %}</a>
        написал вам
        <a class="link-secondary" href="{% url 'posts:post_detail' comment.post.id %}">комментарий</a>.
        <span style="float: right" class="text-muted small">{{ comment.pub_date | naturalday }} в {{ comment.pub_date|date:'H:m' }}</span>
    </li>
      {% endfor %}
      {% if last_comments.count > 4 %}
    <li class="list-group-item">
      Еще {{ last_comments.count | add:'-4' }}
    </li>
      {% endif %}
  </ul>
</div>
<br>
{% endif %}


{% if last_follows %}
<div class="card">
  <ul class="list-group list-group-flush">
    <dd class="card-header text-muted">Подписчики</dd>
      {% for follow in last_follows|slice:':4' %}
    <li class="list-group-item"><a class="link-secondary" href="{% url 'posts:profile' follow.user %}">
        {% if follow.user.first_name %}{{ follow.user.first_name }}{% else %}{{ follow.user }}{% endif %}</a>
        подписался на ваши обновления.
        <span style="float: right" class="text-muted small">{{ follow.pub_date | naturalday }} в {{ follow.pub_date|date:'H:m' }}</span>
    </li>
      {% endfor %}
      {% if last_follows.count > 4 %}
    <li class="list-group-item">
      Еще {{ last_follows.count | add:'-4' }}
    </li>
      {% endif %}
  </ul>
</div>
{% endif %}


{% endblock %}

yatube/templates/users/includes/info_likes.html
{% extends 'users/user_info.html' %}
{% load static %}
{% load thumbnail %}
{% block header %}
Избранное
{% endblock %}
{% block user %}


{% for like in user.likes.all %}

<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      {% if like.post.video %}
      <img src="{% static 'img/video.png' %}" class="img-fluid rounded-start" alt="...">
      {% elif not like.post.image %}
      <img src="{% static 'img/noimage.png' %}" class="img-fluid rounded-start" alt="...">
      {% else %}
      {% endif %}
        {% thumbnail like.post.image "960x670" crop="center" as im %}
      <a href="{% url 'posts:post_detail' like.post.id %}">
      <img src="{{ im.url }}" class="img-fluid rounded-start" alt="...">
        </a>
        {% endthumbnail %}
    </div>
    <div class="col-md-8">
      <div class="card-body">
        {% if like.post.group %}<h5 class="card-title">{{ like.post.group }}</h5>{% endif %}
        <p class="card-text"><a class="text-muted" href="{% url 'posts:post_detail' like.post.id %}">{{ like.post.text|slice:':200' }}</a></p>
        <p class="card-text"><small class="text-muted">{{ like.post.pub_date }}</small></p>
          {% if like.post.comments.count > 0 %}
        <p class="card-text"><small class="text-muted"><a class="text-muted" href="{% url 'posts:post_detail' like.post.id %}">Комментарии: {{ like.post.comments.count }}</a></small></p>
          {% endif %}
      </div>
    </div>
  </div>
</div>
{% endfor %}


{% endblock %}

yatube/templates/users/includes/info_posts.html
{% extends 'users/user_info.html' %}
{% load static %}
{% load thumbnail %}
{% block header %}
Последние посты
{% endblock %}
{% block user %}
{% for post in user.posts.all|slice:':4' %}
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      {% if not post.image %}
      <img src="{% static 'img/noimage.png' %}" class="img-fluid rounded-start" alt="...">
      {% endif %}
        {% thumbnail post.image "960x670" crop="center" as im %}
      <a href="{% url 'posts:post_detail' post.id %}">
      <img src="{{ im.url }}" class="img-fluid rounded-start" alt="...">
        </a>
        {% endthumbnail %}
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ post.group }}</h5>
        <p class="card-text"><a class="text-muted" href="{% url 'posts:post_detail' post.id %}">{{ post.text|slice:':200' }}</a></p>
        <p class="card-text"><small class="text-muted">{{ post.pub_date }}</small></p>
          {% if post.comments.count > 0 %}
        <p class="card-text"><small class="text-muted"><a class="text-muted" href="{% url 'posts:post_detail' post.id %}">Комментарии: {{ post.comments.count }}</a></small></p>
          {% endif %}
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}