yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthor.as_view(), name='author'),
    path('tech/', views.AboutTech.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

CACHE_SEC = 0

urlpatterns = [
    path('', views.PostIndex.as_view(),
         name='index'),
    path('group/<slug:slug>/',
         views.PostGroup.as_view(),
         name='group_list'),
    path('profile/<str:username>/',
         views.PostProfile.as_view(),
         name='profile'),
    path('posts/<int:post_id>/', views.PostDetail.as_view(),
         name='post_detail'),
    path('create/', views.PostCreate.as_view(),
         name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.PostCommentAdd.as_view(),
         name='add_comment'),
    path('follow/', views.FollowIndex.as_view(),
         name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.ProfileFollow.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.ProfileUnfollow.as_view(),
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/like/',
        views.LikePost.as_view(),
        name='post_like'
    ),
    path(
        'posts/<int:post_id>/unlike/',
        views.UnlikePost.as_view(),
        name='post_unlike'
    ),
    path('posts/<int:post_id>/delete/', views.PostDelete.as_view(),
         name='post_delete'),
    path('posts/com/<int:comment_id>/delete/',
         views.CommentDelete.as_view(),
         name='comment_delete'),
    path('search/', views.PostTextSearch.as_view(), name='search')
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordChangeView
)
from django.views.generic import TemplateView
from .views import UserEditor
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_change/done/',
        PasswordChangeView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    # path('info/', TemplateView.as_view(
    #     template_name='users/includes/info_last.html',
    # ),
    #      name='info_last'
    #      ),
    path('info/', views.UserInfo.as_view(), name='info_last'),
    path('user/edit/', UserEditor.as_view(), name='user_edit'),
    path('info/comments/', TemplateView.as_view(
        template_name='users/includes/info_comments.html'
    ), name='info_comments'),
    path('info/posts/', TemplateView.as_view(
        template_name='users/includes/info_posts.html'
    ), name='info_posts'),
    path('info/likes/', TemplateView.as_view(
        template_name='users/includes/info_likes.html'
    ), name='info_likes'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.bad_request'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
  <p>
    <a href="{% url 'about:tech' %}">Технологии</a> | <a href="{% url 'about:author' %}">Об авторе</a>
  </p>
</footer>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>


</header>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Я</span>tube
      </a>
    <div class="navbar-collapse">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav me-4 mb-2 mb-lg-0">
        {% if not user.is_authenticated %}
      <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'users:info_last' %}">
            {% if user.first_name %}
            {{ user.first_name }}
            {% else %}
            {{ user.username }}
            {% endif %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        {% endif %}
        </ul>
      <form class="d-flex" role="search" action="{% url 'posts:search' %}">
        <input class="form-control me-2" type="search" placeholder="Поиск по тексту" aria-label="Search" name="search">
        <button class="btn btn-outline-secondary" type="submit">Искать</button>
      </form>
    </div>
  </div>
</nav>
{% endwith %}