yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthor.as_view(), name='author'),
    path('tech/', views.AboutTech.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

CACHE_SEC = 0

urlpatterns = [
    path('', views.PostIndex.as_view(),
         name='index'),
    path('group/<slug:slug>/',
         views.PostGroup.as_view(),
         name='group_list'),
    path('profile/<str:username>/',
         views.PostProfile.as_view(),
         name='profile'),
    path('posts/<int:post_id>/', views.PostDetail.as_view(),
         name='post_detail'),
    path('create/', views.PostCreate.as_view(),
         name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.PostCommentAdd.as_view(),
         name='add_comment'),
    path('follow/', views.FollowIndex.as_view(),
         name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.ProfileFollow.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.ProfileUnfollow.as_view(),
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/like/',
        views.LikePost.as_view(),
        name='post_like'
    ),
    path(
        'posts/<int:post_id>/unlike/',
        views.UnlikePost.as_view(),
        name='post_unlike'
    ),
    path('posts/<int:post_id>/delete/', views.PostDelete.as_view(),
         name='post_delete'),
    path('posts/com/<int:comment_id>/delete/',
         views.CommentDelete.as_view(),
         name='comment_delete'),
    path('search/', views.PostTextSearch.as_view(), name='search')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.bad_request'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatedModel
from django.urls import reverse
from embed_video.fields import EmbedVideoField

User = get_user_model()


class Group(models.Model):
    objects = None
    title = models.CharField(
        max_length=200,
        verbose_name='Название тематики',
    )
    slug = models.SlugField(
        unique=True, null=False,
        verbose_name='Slug-ссылка'
    )
    description = models.TextField(
        verbose_name='Описание', null=True
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('group', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(CreatedModel):
    objects = None
    text = models.TextField(
        verbose_name='Пост',
        help_text='Введите текст вашего сообщения.',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group, on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу, необязательно.'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Загрузите картинку'
    )
    video = EmbedVideoField(
        blank=True,
        null=True,
        help_text='Вставьте ссылку на видео',
        verbose_name='Видео'
    )
    edit_date = models.DateTimeField(
        'Дата редактирования',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ["-pub_date"]
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(CreatedModel):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    def __str__(self):
        return self.text[:60]

    class Meta:
        ordering = ["-pub_date"]


class Follow(CreatedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )


class Like(CreatedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='likes'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='likes'
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = 'Нет'
        self.fields['text'].widget.attrs['rows'] = 4

    class Meta:
        model = Post
        fields = ('text', 'group', 'image', 'video')

        def clean_subject(self):
            data = self.cleaned_data['video']
            if 'youtu' not in data.lower():
                raise forms.ValidationError(
                    'Видео должно быть из YoutTube')
            return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.TextInput(),
        }

yatube/posts/views.py
from datetime import datetime

from django.shortcuts import get_object_or_404, redirect
from .models import Post, Group, User, Follow, Comment, Like
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm, CommentForm
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    FormView,
    View
)

P_COUNT = 10  # количество постов для пагинатора


class DataMixin:
    """Поключает пагинатор"""
    model = Post
    paginate_by = P_COUNT


class PostIndex(DataMixin, ListView):
    """Главная страница."""
    template_name = 'posts/index.html'

    def get_queryset(self):
        return Post.objects.select_related('author', 'group')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostIndex, self).get_context_data(**kwargs)
        context['form'] = PostForm
        return context

    def post(self, request):
        form = PostForm(request.POST or None,
                        files=request.FILES or None,
                        )
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = self.request.user
            obj.save()
        return redirect(
            'posts:profile', request.user)


class PostGroup(DataMixin, ListView):
    """Страница с постами группы."""
    template_name = 'posts/group_list.html'

    def get_queryset(self):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        return Post.objects.filter(
            group=group
        ).select_related('author', 'group').all()


class PostProfile(DataMixin, ListView):
    """Страница с постами пользователя."""
    template_name = 'posts/profile.html'
    author: str

    def get_queryset(self):
        self.author = get_object_or_404(
            User, username=self.kwargs.get('username'))
        return Post.objects.filter(
            author=self.author
        ).select_related('author', 'group')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.author
        if self.request.user.is_authenticated:
            context['following'] = Follow.objects.filter(
                user=self.request.user, author=self.author
            ).exists()
        return context


class PostDetail(DetailView):
    """Страница поста."""
    model = Post
    template_name = 'posts/post_detail.html'
    pk_url_kwarg = 'post_id'

    def get_context_data(self, **kwargs):
        post = get_object_or_404(
            Post, pk=self.kwargs['post_id'])
        context = {
            'form': PostForm(self.request.POST or None,
                             files=self.request.FILES or None,
                             instance=post),
            'comments_form': CommentForm(self.request.POST or None),
            'comments': post.comments.all().select_related('author', ),
            'post': post,
            'following': Follow.objects.filter(
                user=self.request.user, author=post.author
            ).exists() if self.request.user.is_authenticated else False
        }
        return context

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        form = PostForm(request.POST or None,
                        files=request.FILES or None,
                        instance=post
                        )
        if form.is_valid() and request.user == post.author:
            obj = form.save(commit=False)
            obj.edit_date = datetime.now()
            obj.save()
        return redirect(
            'posts:post_detail', kwargs.get('post_id')
        )


class PostCreate(LoginRequiredMixin, CreateView):
    """Страница создания поста."""
    form_class = PostForm
    template_name = 'posts/create_post.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return redirect('posts:profile', self.request.user)

    def get_object(self, queryset=None):
        post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        return post

class PostCommentAdd(LoginRequiredMixin, FormView):
    """Форма добавления комментария."""
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        comment.save()
        return redirect('posts:post_detail', post_id=self.kwargs['post_id'])

    def get(self, request, *args, **kwargs):
        return redirect('posts:post_detail', post_id=self.kwargs['post_id'])


class FollowIndex(LoginRequiredMixin, DataMixin, ListView):
    template_name = 'posts/follow_index.html'
    context_object_name = 'post'

    def get_queryset(self):
        return Post.objects.filter(author__following__user=self.request.user)


class ProfileFollow(LoginRequiredMixin, View):
    def get(self, request, username):
        user = request.user
        author = get_object_or_404(User, username=username)
        is_follower = Follow.objects.filter(user=user, author=author)
        if user != author and not is_follower.exists():
            Follow.objects.create(user=user, author=author)
        return redirect(request.META.get('HTTP_REFERER'))


class ProfileUnfollow(LoginRequiredMixin, View):
    def get(self, request, username):
        author = get_object_or_404(User, username=username)
        is_follower = Follow.objects.filter(user=request.user, author=author)
        is_follower.delete()
        return redirect(request.META.get('HTTP_REFERER'))


class PostDelete(View):
    def get(self, request, post_id):
        post = Post.objects.get(id=post_id)
        if post.author != request.user:
            return redirect(request.META.get('HTTP_REFERER'))
        post.delete()
        return redirect(request.META.get('HTTP_REFERER'))


class CommentDelete(View):
    def get(self, request, comment_id):
        """Функция удаления комментария."""
        comment = Comment.objects.get(id=comment_id)
        if comment.author != request.user:
            return redirect(request.META.get('HTTP_REFERER'))
        comment.delete()
        return redirect(request.META.get('HTTP_REFERER'))


class PostTextSearch(DataMixin, ListView):
    template_name = 'posts/search.html'

    def get_queryset(self):
        return Post.objects.filter(text__contains=self.get_object())

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.get_object()
        return context

    def get_object(self):
        search_query = self.request.GET.get('search', )
        return search_query


class LikePost(LoginRequiredMixin, View):
    def get(self, request, post_id):
        user = request.user
        post = get_object_or_404(Post, pk=post_id)
        is_liked = Like.objects.filter(user=user, post=post)
        if not is_liked.exists():
            Like.objects.create(user=user, post=post)
        return redirect(request.META.get('HTTP_REFERER'))


class UnlikePost(LoginRequiredMixin, View):
    def get(self, request, post_id):
        user = request.user
        post = get_object_or_404(Post, pk=post_id)
        is_liked = Like.objects.filter(user=user, post=post)
        is_liked.delete()
        return redirect(request.META.get('HTTP_REFERER'))

yatube/templates/posts/includes/comments.html
{% load user_filters %}
{% load humanize %}
<div class="card my-4">
<h7 class="card-header">Комментарии:</h7>
  <div class="card-body">
    {% for comment in comments %}
<div class="input-group mb-3">
  <div class="input-group-text">
    <a class="link-secondary" href="{% url 'posts:profile' comment.author.username %}">
      {% if comment.author.first_name %}
    {{ comment.author.first_name }} {{ comment.author.last_name|slice:':1' }}
      {% else %}
      {{ comment.author.username }}
      {% endif %}
    </a>
  </div>
  <div class="form-control">
    {{ comment.text }}
    <span class="small text-muted" style="float: right">
      {{ comment.pub_date|naturalday }} в {{ comment.pub_date|date:'H:m' }}
      {% if comment.author == user %}
      <a href="{% url 'posts:comment_delete' comment.pk %}" type="button" class="btn-close" aria-label="Close"></a>
    {% endif %}
    </span>
  </div>
</div>
{% endfor %}
{% if user.is_authenticated %}
    <form method="post" action="{% url 'posts:add_comment' post.id %}">
      {% csrf_token %}
      <div class="form-group mb-2">
        {{ comments_form.text|addclass:"form-control" }}
      </div>
      <button type="submit" class="btn btn-secondary">Отправить</button>
    </form>
  </div>
{% endif %}
  </div>

yatube/templates/posts/includes/create_post.html
{% load user_filters %}
<div class="row justify-content-center">
    <div class="col-md-11 p-1">
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endif %}
        <div class="card-body ">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-1 p-1">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger" >*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                <small id="{{ field.id_for_label}}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-secondary">
            {% if is_edit == 'True' %}
            Добавить
            {% else %}
            Сохранить
            {% endif %}
        </button>
      </div>
    </form>
  </div>
</div>
  </div>

yatube/templates/posts/includes/empty_page.html
<article>
    <div class="card my-4">
      <h7 class="card-header">
        Нет контента.
      </h7>
      <div class="card-body">
      <p>
       <a href="{% url 'posts:post_create' %}">Создайте пост</a>
      </p>
      </div>
    </div>
  </article>

yatube/templates/posts/includes/follow_botton.html
{% if user.is_authenticated %}
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-secondary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
  {% endif %}
{% endif %}

yatube/templates/posts/includes/likes.html
{% load user_filters %}
{% if user.is_authenticated %}
  {% if user.likes.all|in_likes:post != None %}
    {% with user.likes.all|in_likes:post as like %}
      {% if like.post.id == post.id %}
        <a class="link-secondary" href="{% url 'posts:post_unlike' post.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/></svg></a>
        <small class="text-muted">{{ post.likes.count }}</small>
      {% endif %}
    {% endwith %}

  {% else %}
    <a class="link-secondary" href="{% url 'posts:post_like' post.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16"><path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg></a>
    {% if post.likes.count != 0 %}<small class="text-muted">{{ post.likes.count }}</small>{% endif %}
  {% endif %}
{% else %}
  {% if post.likes.all.count == 0 %}
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16"><path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>
  {% else %}
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#888888" class="bi bi-heart-fill" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/></svg>
    <small class="text-muted">{{ post.likes.count }}</small>
  {% endif %}
{% endif %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/post_detail_post.html
{% load embed_video_tags %}
{% load thumbnail %}
<div class="row">
  {% if detail_flag == 'True' %}
  {% include 'posts/includes/post_detail_sidebar.html' %}
  {% endif %}
  <article class="col-12 col-md-9">
    <div class="card my-4">
      {% if post.image or post.video %}
      <h7 class="card-header">
        {% thumbnail post.image "1080x381" crop="center" upscale=True as im %}
        <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <img class="card-img my-2" src="{{ im.url }}">
          <figcaption class="figure-caption">Что бы открыть изображение - кликните по нему.</figcaption>
        </a>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-xl">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Оригинальное изображение</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
              </div>
              <div class="modal-body">
                <img class="card-img my-2" src="{{ post.image.url }}">
              </div>
            </div>
          </div>
        </div>
        {% endthumbnail %}

        {% if post.video %}
          {% video post.video '100% x 600' %}
        {% endif %}
      </h7>
      {% else %}
        <h7 class="card-header"><b>Пост:</b></h7>
      {% endif %}
      <div class="card-body">
        <p class="blockquote">
          {{ post.text | linebreaksbr }}
        </p>
      </div>
    </div>
    {% if detail_flag == 'True' %}
      {% include 'posts/includes/comments.html' %}
    {% endif %}
  </article>
</div>
<br>

yatube/templates/posts/includes/post_detail_sidebar.html
{% load user_filters %}
<aside class="col-12 col-md-3">
<div class="card my-4">
  <dd class="list-group list-group-flush">
    <li class="card-header">
      Информация:
    </li>
    <li class="list-group-item">
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.edit_date %}
    <li class="list-group-item">
      Отредактирован: {{ post.edit_date|date:"d E Y" }}
    </li>
    {% endif %}
    {% if post.group %}
    <li class="list-group-item">
      Группа:
      <a class="link-secondary" href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
    </li>
    {% endif %}
    <li class="list-group-item">
      Автор: <a class="link-secondary" href="{% url 'posts:profile' post.author %}">{% if post.author.first_name %}{{ post.author.first_name }}{% else %}{{post.author}}{% endif %}</a>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Всего постов автора: {{ post.author.posts.count }}
    </li>
    <li class="list-group-item">
      <a class="link-secondary" href="{% url 'posts:profile' post.author %}">
        все посты пользователя
      </a>
    </li>
</div>
  </dd>
  {% if post.author.following.all %}
  <div class="card my-4">
    <dd class="list-group list-group-flush">
      <li class="card-header">
        Подписчики: {{ post.author.following.count }}
      </li>
      {% for i in post.author.following.all %}
      <li class="list-group-item">
        <a class="link-secondary" href="{% url 'posts:profile' i.user %}">
          {% if not i.user.first_name %}
          {{ i.user }}
          {% else %}
          {{ i.user.first_name }}
          {% endif %}
        </a>
      </li>
      {% endfor %}
    </dd>
  </div>
  {% endif %}
  {% if post.likes.all != None %}
  <div class="card my-4">
    <dd class="list-group list-group-flush">
      <li class="card-header">
        Лайки: {{ post.likes.count }}
      </li>
      {% for lower in post.likes.all|slice:':5' %}
      <li class="list-group-item">
        <a class="link-secondary" href="{% url 'posts:profile' lower.user %}">{%if lower.user.first_name %} {{ lower.user.first_name }}{% else %} {{ lower.user }}{% endif %}</a>
      </li>
       {% if post.likes.count > 5 %}
      <li class="list-group-item">
        и еще {{ post.likes.count|add:'-5' }}
      </li>
      {%endif %}
      {% endfor %}
    </dd>
  </div>
  {% endif %}
{% if post.author == user %}
   <a class="btn btn-secondary" type="button" data-bs-toggle="modal" data-bs-target="#editPost">
          Редактировать запись
        </a>
        <div class="modal fade" id="editPost" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-xl">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Редактирование записи</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
              </div>
              <div class="modal-body">
                {% include 'posts/includes/create_post.html' %}
              </div>
            </div>
          </div>
        </div>
<a class="btn btn-secondary" href="{% url 'posts:index' %}">
  Удалить
</a></p>
<hr>
{%endif %}
{% if user.is_authenticated %}
{% if request.user != post.author %}
  {% if following %}
    <a class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' post.author.username %}" role="button">
      Отписаться
    </a>
  {% else %}
      <a class="btn btn-lg btn-secondary"
        href="{% url 'posts:profile_follow' post.author.username %}" role="button">
        Подписаться
      </a>
   {% endif %}
{% endif %}
{% endif %}
</aside>

yatube/templates/posts/includes/posts_form.html
{% load thumbnail %}
{% load humanize %}
{% load embed_video_tags %}
<article>
  <div class="card my-4">
  <h7 class="card-header">
  <dd>
    <div align="right" style="float:right;">
      <font class="figure-caption">
        {{ post.pub_date|naturalday }} в {{ post.pub_date|date:'H:m' }}
        <p>{% if post.edit_date %}(изменен){% endif %}</p>
      </font>
    </div>
    {% if author_flag == 'True' %}
    <li>
      Автор:
      <a class="link-secondary" href="{%url 'posts:profile' post.author %}">
        {% if post.author.first_name %}
        {{ post.author.first_name }} {{ post.author.last_name|slice:':1' }}.
        {% else %}
        {{ post.author.username }}
        {% endif %}
      </a>
    </li>
    {% endif %}
    {% if group_flag == 'True' %}
    {% if post.group and group_flag %}
    <li>
        Группа:
        <a class="link-secondary" href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
    </li>
    {% endif %}
    {% endif %}
  </dd>
  </h7>
<div class="card-body">
  {% thumbnail post.image "1080x381" crop="center" upscale=True as im %}
    <a href="{% url 'posts:post_detail' post.pk %}">
      <img class="card-img my-2" src="{{ im.url }}" style="object-fit: contain; width: 100%">
    </a>
  {% endthumbnail %}



  {% if post.video %}
  <div class="card-img my-2">{% video post.video '100% x 400' %}</div>
  {% endif %}


  <div class="fw-light">
    <p>
      {{ post.text|linebreaks|slice:':500' }}{% if post.text|length > 500 %}... <a class="text-muted" href="{% url 'posts:post_detail' post.id %}">читать далее</a>{% endif %}
    </p>
    <span style="float: right">{% include 'posts/includes/likes.html'%}</span>
  </div>
</div>
<h7 class="card-footer">
  <dt>
    {% if post.comments.count > 0 %}
    <dd>
  <a class="link-secondary" href="{% url 'posts:post_detail' post.pk %}">Комментарии: {{ post.comments.count }}</a>
    </dd>
      {% endif %}
    <dd>
    <a class="link-secondary" href="{% url 'posts:post_detail' post.pk %}">подробная инфомация</a>
      {% if post.author == user %}
    <span style="float:right;">
      <a href="{% url 'posts:post_delete' post.pk %}" type="button" class="btn-close" aria-label="Close"></a>
  </span>
    {% endif %}
    </dd>
  </dt>
</h7>
  </div>
</article>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
{% with request.resolver_match.view_name as view_name %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link link-secondary  {% if view_name  == 'posts:index' %}active{% endif %}"
          href="{% url 'posts:index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-secondary {% if view_name  == 'posts:follow_index' %}active{% endif %}"
           href="{% url 'posts:follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endwith %}
{% endif %}