yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthor.as_view(), name='author'),
    path('tech/', views.AboutTech.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

CACHE_SEC = 0

urlpatterns = [
    path('', views.PostIndex.as_view(),
         name='index'),
    path('group/<slug:slug>/',
         views.PostGroup.as_view(),
         name='group_list'),
    path('profile/<str:username>/',
         views.PostProfile.as_view(),
         name='profile'),
    path('posts/<int:post_id>/', views.PostDetail.as_view(),
         name='post_detail'),
    path('create/', views.PostCreate.as_view(),
         name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.PostCommentAdd.as_view(),
         name='add_comment'),
    path('follow/', views.FollowIndex.as_view(),
         name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.ProfileFollow.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.ProfileUnfollow.as_view(),
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/like/',
        views.LikePost.as_view(),
        name='post_like'
    ),
    path(
        'posts/<int:post_id>/unlike/',
        views.UnlikePost.as_view(),
        name='post_unlike'
    ),
    path('posts/<int:post_id>/delete/', views.PostDelete.as_view(),
         name='post_delete'),
    path('posts/com/<int:comment_id>/delete/',
         views.CommentDelete.as_view(),
         name='comment_delete'),
    path('search/', views.PostTextSearch.as_view(), name='search')
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordChangeView
)
from django.views.generic import TemplateView
from .views import UserEditor
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_change/done/',
        PasswordChangeView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    # path('info/', TemplateView.as_view(
    #     template_name='users/includes/info_last.html',
    # ),
    #      name='info_last'
    #      ),
    path('info/', views.UserInfo.as_view(), name='info_last'),
    path('user/edit/', UserEditor.as_view(), name='user_edit'),
    path('info/comments/', TemplateView.as_view(
        template_name='users/includes/info_comments.html'
    ), name='info_comments'),
    path('info/posts/', TemplateView.as_view(
        template_name='users/includes/info_posts.html'
    ), name='info_posts'),
    path('info/likes/', TemplateView.as_view(
        template_name='users/includes/info_likes.html'
    ), name='info_likes'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.bad_request'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        # Add all the fields you want a user to change
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView, UpdateView, TemplateView
from django.urls import reverse_lazy
from .forms import CreationForm, UserUpdateForm
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from posts.models import Post, Like, Comment, Follow

User = get_user_model()


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class UserEditor(UpdateView):
    model = User
    template_name = 'users/user_edit.html'
    extra_context = {'is_edit': True}
    form_class = UserUpdateForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None,
                               instance=request.user
                               )
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
        return redirect(
            'users:info_last'
        )

    def get_object(self, queryset=None):
        print(User.objects.get(username=self.request.user.username))
        user = User.objects.get(username=self.request.user.username)
        return user


class UserInfo(TemplateView):
    template_name = 'users/includes/info_last.html'

    def get_context_data(self, **kwargs):
        context = super(UserInfo, self).get_context_data(**kwargs)
        user = self.request.user
        posts = Post.objects.filter(author=user)
        last_likes = Like.objects.filter(post__author=user).exclude(user=user)
        last_comments = Comment.objects.exclude(author=user).filter(post__author=user)
        last_follows = Follow.objects.filter(author=user)

        context.update({
            'posts': posts,
            'last_likes': last_likes,
            'last_comments': last_comments,
            'last_follows': last_follows,
        })
        return context

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}ЯTube|Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}>
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}ЯTube|Пароль изменен{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}ЯTube|Восстановление пароля{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'users:password_change_done' %}">
                  {% csrf_token %}
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}ЯTube|Пароль сохранен{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <form action="{% url 'users:login' %}">
                  <button type="submit" class="btn btn-primary">Войти</button>
                </form>
<!--                <a href="{% url 'users:login' %}">войти</a>-->
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}ЯTube|Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post">{% csrf_token %}
<!--                  <input type="hidden" name="csrfmiddlewaretoken" value="">-->
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>

{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endif %}

{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends 'users/user_info.html' %}
{% block header %}
Смена пароля
{% endblock %}
{% block user %}
{% load user_filters %}
          <div class="col-md-12 p-0">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'users/user_info.html' %}
{% block header %}
Смена пароля
{% endblock %}
{% block user %}
{% load user_filters %}
          <div class="col-md-12 p-0">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались

                <form method="post">
                  {% csrf_token %}
<!--                  <input type="hidden" name="csrfmiddlewaretoken" value="">-->
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-secondary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}ЯTube|Регистрация{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/user_edit.html
{% extends 'users/user_info.html' %}
{% block header %}
Редактировать профиль
{% endblock %}
{% block user %}
          <div class="card-body position-relative top-0">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:user_edit' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help"
                         class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
                  <a class="link-secondary" href="{% url 'users:password_reset_form' %}">Сменить пароль</a>
              <div class="col-md-6 offset-md-5">
                <button type="submit" class="btn btn-secondary">
                  Сохранить
                </button>
              </div>
            </form>
          </div> <!-- card body -->
{% endblock %}

yatube/templates/users/user_info.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
<aside class="col-12 col-md-3">
<div class="card my-4">
  <dd class="list-group list-group-flush">
    <li class="card-header">
      Информация
      <span style="float:right;">
        <a class="link-secondary" href="{% url 'users:user_edit' %}">Ред.</a>
      </span>
    </li>
    <li class="list-group-item">
      <span class="text-muted">Имя:</span> {{ user.get_full_name }}
    </li>
    <li class="list-group-item">
      <span class="text-muted">E-mail:</span> {{ user.email }}
    </li>
    <li class="list-group-item">
      <span class="text-muted">Имя пользователя:</span> {{ user.username }}
    </li>
    <li class="list-group-item">
      <span class="text-muted">Дата регистрации:</span> {{ user.date_joined|date:'j M Y' }}
    </li>
  </dd>
</div>

<div class="card my-4">
  <dd class="list-group list-group-flush">
    <li class="card-header">
        Контент
    </li>
    <li class="list-group-item">
      <a class="link-secondary" href="{% url 'users:info_posts' %}">Посты: {{ user.posts.count }}</a>
    </li>
    <li class="list-group-item">
      <a class="link-secondary" href="{% url 'users:info_comments' %}">Комментарии: {{ user.comments.count }}</a>
    </li>
    {% if user.likes.all != None %}
      <li class="list-group-item">
        <a class="link-secondary" href="{% url 'users:info_likes' %}">Избранное: {{ user.likes.count }}</a>
      </li>
      {% endif %}
  </dd>
</div>
  {% if user.following.all %}
  <div class="card my-4">
    <dd class="list-group list-group-flush">
      <li class="card-header">
        Подписчики ({{ user.following.count }}):
      </li>
      {% for i in user.following.all %}
      <li class="list-group-item">
        <a class="link-secondary" href="{% url 'posts:profile' i.user %}">
          {% if not i.user.get_full_name %}
          {{ i.user.username }}
          {% else %}
          {{ i.user.get_full_name }}
          {% endif %}
        </a>
      </li>
      {% endfor %}
    </dd>
  </div>
    {% endif %}
    {% if user.follower.all %}
  <div class="card my-4">
    <dd class="list-group list-group-flush">
      <li class="card-header">
        Мои подписки ({{ user.follower.count }}):
      </li>
      {% for i in user.follower.all %}
      <li class="list-group-item">
        <a class="link-secondary" href="{% url 'posts:profile' i.author %}">
          {% if not i.author.get_full_name %}
          {{ i.author.username }}
          {% else %}
          {{ i.author.get_full_name }}
          {% endif %}
        </a>
          <span style="float:right;">
            <a href="{% url 'posts:profile_unfollow' i.author.username %}" type="button" class="btn-close" aria-label="Close"></a>
          </span>
      </li>
      {% endfor %}
    </dd>
  </div>
    {% endif %}
<hr>
</aside>


  <article class="col-12 col-md-9">
    <div class="card my-4">
      <h7 class="card-header">
        {% block header %}
        HEADER
        {% endblock %}
      </h7>
      <div class="card-body">
       {% block user %}
        BLOCK
        {% endblock %}
      </div>
    </div>
  </article>
</div>
{% endblock %}